language: java

cache:
  directories:
  - "$HOME/.cache"

before_install:
  - wget http://apache.mirrors.spacedump.net/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -qq apache-maven-3.5.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH

install:
  #- mvn -s ./settings-jboss.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
script:
  - mvn -s ./settings-jboss.xml clean install deploy -DretryFailedDeploymentCount=10 -DdeployAtEnd=true 
