language: java

before_install:
  - gem install package_cloud

install:
  #- mvn -s ./settings-jboss.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
script:
  - mvn -s ./settings-jboss.xml clean deploy -DretryFailedDeploymentCount=10 -DdeployAtEnd=true 